package(default_visibility = ["//visibility:public"])

config_setting(
    name = "android_armv7",
    values = {
        "cpu": "armeabi-v7a",
    },
)

config_setting(
    name = "android_arm64",
    values = {
        "cpu": "arm64-v8a",
    },
)

config_setting(
    name = "android_x86",
    values = {
        "cpu": "x86",
    },
)
